name: App
include:
  - app/addons/addons.yml

packages:
  BareKit:
    url: https://github.com/holepunchto/bare-kit-swift
    branch: main
  BareRPC:
    url: https://github.com/holepunchto/bare-rpc-swift
    branch: main

targets:
  App:
    type: application
    platform: macOS
    deploymentTarget: 26.0
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: to.holepunch.bare.ios
        SWIFT_VERSION: 5.0
        CODE_SIGN_STYLE: Automatic
    info:
      path: app/Info.plist

    dependencies:
      - framework: app/frameworks/BareKit.xcframework
      - package: BareKit
      - package: BareRPC

    sources:
      - path: app/App.swift
      - path: app/AppDelegate.swift
      - path: app/app.bundle
        optional: true

      - path: app/js/app.js
        group: app/js

      - path: app/Core/HyperSchemeHandler.swift
        group: app/Core
      - path: app/Core/BareRuntime.swift
      - path: app/Core/RPCClient.swift
      - path: app/Core/DriveService.swift
      - path: app/Core/BrowserViewModel.swift
      - path: app/Core/BrowserTab.swift
      - path: app/Core/HyperNavigationDecider.swift
      - path: app/Core/AppModel.swift

      - path: app/Core/Root/ContentView.swift
        group: app/Core/Root
        optional: true
    scheme:
      preActions:
        - name: Link & pack
          script: |

            PATH="${PATH}" "${PWD}/node_modules/.bin/bare-link" \
              --host darwin-arm64 \
              --host ios-arm64 \
              --host ios-arm64-simulator \
              --out ${PWD}/app/addons/ \
              ${PWD}

            PATH="${PATH}" "${PWD}/node_modules/.bin/bare-pack" \
              --host darwin-arm64 \
              --host ios-arm64 \
              --host ios-arm64-simulator \
              --linked \
              --base ${PWD} \
              --out ${PWD}/app/app.bundle \
              ${PWD}/app/js/app.js
