name: App
include:
  - app/addons/addons.yml

targets:
  App:
    type: application
    platform: macOS
    deploymentTarget: 26.0
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: to.holepunch.bare.ios
        SWIFT_VERSION: 5.0
        CODE_SIGN_STYLE: Automatic
        SWIFT_OBJC_BRIDGING_HEADER: "$(SRCROOT)/app/briding-header.h"
    info:
      path: app/Info.plist

    dependencies:
      - framework: app/frameworks/BareKit.framework

    sources:
      - path: app/App.swift
      - path: app/app.js
      - path: app/app.bundle
      - path: app/briding-header.h
      - path: app/IPC.swift
      - path: app/Worklet.swift

      - path: app/Core/Scheme.swift
        group: app/Core
      - path: app/Core/Worker.swift
      - path: app/Core/IPCViewModel.swift

      - path: app/Core/Root/ContentView.swift
        group: app/Core/Root
        optional: true
    scheme:
      preActions:
        - name: Link
          script: |
            PATH="${PATH}" "${PWD}/node_modules/.bin/bare-link" \
              --preset darwin \
              --out ${PWD}/app/addons \
              ${PWD}
        - name: Pack
          script: |
            PATH="${PATH}" "${PWD}/node_modules/.bin/bare-pack" \
              --preset darwin \
              --linked \
              --base ${PWD} \
              --out ${PWD}/app/app.bundle \
            ${PWD}/app/app.js
